import type { Product, Category, Grower, Review, Order } from "./types"

export const growers: Grower[] = [
  {
    id: "g1",
    slug: "domaine-du-soleil",
    name: "Pierre Dumont",
    avatar: "/growers/pierre.svg",
    farmName: "Domaine du Soleil",
    region: "Provence",
    bio: "Cultivateur de chanvre biologique depuis 2016 dans les collines de Provence. Nos plants beneficient d'un ensoleillement exceptionnel et d'un sol argilo-calcaire ideal.",
    story: "Apres 20 ans dans l'agriculture biologique, Pierre a converti ses terres provencales a la culture du chanvre CBD en 2016. Son domaine de 12 hectares surplombe la vallee du Luberon, offrant des conditions de croissance optimales. Chaque plant est soigne a la main, de la semence a la recolte, pour garantir une qualite exceptionnelle.",
    certifications: ["AB", "EU Bio", "Ecocert"],
    verified: true,
    productCount: 8,
    joinedYear: 2016,
    farmPhoto: "/growers/domaine-soleil.svg",
  },
  {
    id: "g2",
    slug: "ferme-des-bruyeres",
    name: "Marie Lefevre",
    avatar: "/growers/marie.svg",
    farmName: "Ferme des Bruyeres",
    region: "Bretagne",
    bio: "Agriculture regenerative en Bretagne. Notre chanvre pousse en harmonie avec la lande bretonne, nourri par le climat oceanique doux.",
    story: "Marie a fonde la Ferme des Bruyeres en 2018, appliquant les principes de l'agriculture regenerative a la culture du chanvre. Situee pres de la cote d'Armor, la ferme profite d'un microclimat unique. Marie est pionniere dans les techniques de permaculture appliquees au chanvre, et ses produits sont reconnus pour leur profil terpeneque exceptionnel.",
    certifications: ["AB", "EU Bio", "Demeter"],
    verified: true,
    productCount: 6,
    joinedYear: 2018,
    farmPhoto: "/growers/ferme-bruyeres.svg",
  },
  {
    id: "g3",
    slug: "chanvrerie-alsacienne",
    name: "Thomas Muller",
    avatar: "/growers/thomas.svg",
    farmName: "Chanvrerie Alsacienne",
    region: "Alsace",
    bio: "Tradition et innovation au coeur de l'Alsace. Nos methodes combinent savoir-faire ancestral et techniques modernes d'extraction.",
    story: "Issu d'une famille d'agriculteurs alsaciens depuis quatre generations, Thomas a modernise l'exploitation familiale en se tournant vers le chanvre CBD en 2017. La Chanvrerie Alsacienne cultive des varietes speciales adaptees au terroir alsacien, produisant des fleurs d'une densite et d'un arome remarquables. Leur laboratoire sur place permet un controle qualite rigoureux a chaque etape.",
    certifications: ["AB", "EU Bio"],
    verified: true,
    productCount: 10,
    joinedYear: 2017,
    farmPhoto: "/growers/chanvrerie.svg",
  },
  {
    id: "g4",
    slug: "jardin-occitan",
    name: "Sophie Garnier",
    avatar: "/growers/sophie.svg",
    farmName: "Le Jardin Occitan",
    region: "Occitanie",
    bio: "Culture artisanale dans les terres ocres d'Occitanie. Specialiste des varietes riches en CBD pour le bien-etre quotidien.",
    story: "Pharmacienne de formation, Sophie a fonde Le Jardin Occitan en 2019 pour proposer des produits CBD de qualite pharmaceutique. Son approche scientifique de la culture, combinee a son respect profond de la terre occitane, produit des extraits d'une purete exceptionnelle.",
    certifications: ["AB", "EU Bio", "Nature & Progres"],
    verified: true,
    productCount: 5,
    joinedYear: 2019,
    farmPhoto: "/growers/jardin-occitan.svg",
  },
]

export const categories: Category[] = [
  { id: "c1", slug: "resines", name: "Resines", description: "Resines CBD pressees artisanalement", productCount: 12, image: "/categories/resines.svg" },
  { id: "c2", slug: "fleurs", name: "Fleurs", description: "Fleurs de chanvre CBD sechees naturellement", productCount: 18, image: "/categories/fleurs.svg" },
  { id: "c3", slug: "huiles-bio", name: "Huiles Bio", description: "Huiles CBD biologiques full spectrum", productCount: 8, image: "/categories/huiles.svg" },
  { id: "c4", slug: "infusions", name: "Infusions", description: "Melanges d'herbes et chanvre CBD", productCount: 6, image: "/categories/infusions.svg" },
  { id: "c5", slug: "baumes", name: "Baumes", description: "Soins topiques au CBD", productCount: 5, image: "/categories/baumes.svg" },
  { id: "c6", slug: "bonbons", name: "Bonbons", description: "Confiseries artisanales au CBD", productCount: 7, image: "/categories/bonbons.svg" },
]

export const products: Product[] = [
  {
    id: "p1",
    slug: "resine-gold-hash-cbd",
    name: "Resine Gold Hash CBD",
    price: 8.9,
    regularPrice: 12.9,
    images: ["/products/resine-gold-1.svg", "/products/resine-gold-2.svg"],
    category: "Resines",
    categorySlug: "resines",
    description: "Notre resine Gold Hash est pressee artisanalement a partir de trichomes de chanvre cultive en Provence. Son arme doux et terreux offre une experience authentique, avec un taux de CBD de 22% pour une relaxation profonde. Chaque lot est teste en laboratoire pour garantir une purete optimale et un taux de THC inferieur a 0.3%.",
    shortDescription: "Resine pressee artisanalement, 22% CBD, arme terreux et doux",
    features: { cbdPercent: "22%", thcLevel: "<0.3%", origin: "Provence, France", extraction: "Pression a froid" },
    variants: [
      { weight: "1g", price: 8.9, stock: 50 },
      { weight: "3g", price: 23.9, stock: 30 },
      { weight: "5g", price: 36.9, stock: 20 },
      { weight: "10g", price: 65.9, stock: 10 },
    ],
    rating: 4.8,
    reviewCount: 124,
    badges: ["best-seller", "promo"],
    stock: 50,
    grower: { id: "g1", name: "Pierre Dumont", avatar: "/growers/pierre.svg", region: "Provence", verified: true },
    terroir: "Provence",
    harvestDate: "2026-01-20",
    labCertificateUrl: "#",
    organicCertifications: ["AB", "EU Bio"],
    effects: ["Relaxation", "Bien-etre"],
  },
  {
    id: "p2",
    slug: "fleur-lemon-haze-cbd",
    name: "Fleur Lemon Haze CBD",
    price: 6.5,
    images: ["/products/lemon-haze-1.svg", "/products/lemon-haze-2.svg"],
    category: "Fleurs",
    categorySlug: "fleurs",
    description: "La Lemon Haze CBD est une variete sativa reconnue pour ses notes vives d'agrumes et son effet energisant. Cultivee en plein air dans les collines bretonnes, chaque fleur est sechee lentement pour preserver son profil terpenique unique. Ideale pour une utilisation en journee.",
    shortDescription: "Fleur sativa aux notes d'agrumes, 18% CBD, culture plein air",
    features: { cbdPercent: "18%", thcLevel: "<0.2%", origin: "Bretagne, France", extraction: "Sechage naturel" },
    variants: [
      { weight: "1g", price: 6.5, stock: 80 },
      { weight: "3g", price: 17.5, stock: 45 },
      { weight: "5g", price: 27.5, stock: 25 },
      { weight: "10g", price: 49.9, stock: 15 },
    ],
    rating: 4.6,
    reviewCount: 89,
    badges: ["nouveau"],
    stock: 80,
    grower: { id: "g2", name: "Marie Lefevre", avatar: "/growers/marie.svg", region: "Bretagne", verified: true },
    terroir: "Bretagne",
    harvestDate: "2026-01-28",
    labCertificateUrl: "#",
    organicCertifications: ["AB", "EU Bio", "Demeter"],
    effects: ["Bien-etre", "Concentration"],
  },
  {
    id: "p3",
    slug: "huile-cbd-bio-15",
    name: "Huile CBD Bio 15%",
    price: 39.9,
    regularPrice: 49.9,
    images: ["/products/huile-15-1.svg", "/products/huile-15-2.svg"],
    category: "Huiles Bio",
    categorySlug: "huiles-bio",
    description: "Notre huile CBD Bio 15% est extraite a froid a partir de chanvre biologique alsacien. Le spectre complet preserve tous les cannabinoides et terpenes naturels pour un effet d'entourage optimal. Conditionnee dans un flacon en verre ambre avec pipette dosee pour une utilisation precise.",
    shortDescription: "Huile full spectrum 15% CBD, extraction a froid, flacon 10ml",
    features: { cbdPercent: "15%", thcLevel: "<0.2%", origin: "Alsace, France", extraction: "CO2 supercritique" },
    variants: [
      { weight: "10ml", price: 39.9, stock: 40 },
      { weight: "30ml", price: 99.9, stock: 20 },
    ],
    rating: 4.9,
    reviewCount: 203,
    badges: ["best-seller", "promo"],
    stock: 40,
    grower: { id: "g3", name: "Thomas Muller", avatar: "/growers/thomas.svg", region: "Alsace", verified: true },
    terroir: "Alsace",
    harvestDate: "2025-12-15",
    labCertificateUrl: "#",
    organicCertifications: ["AB", "EU Bio"],
    effects: ["Sommeil", "Relaxation", "Douleur"],
  },
  {
    id: "p4",
    slug: "infusion-nuit-paisible",
    name: "Infusion Nuit Paisible",
    price: 12.9,
    images: ["/products/infusion-nuit-1.svg", "/products/infusion-nuit-2.svg"],
    category: "Infusions",
    categorySlug: "infusions",
    description: "Un melange delicat de chanvre CBD, camomille, lavande et passiflore, concu pour favoriser un sommeil reparateur. Chaque sachet contient 2g de melange biologique, soigneusement dose pour une infusion parfaite. Sans cafeine, ideal avant le coucher.",
    shortDescription: "Melange chanvre CBD, camomille et lavande pour le sommeil",
    features: { cbdPercent: "8%", thcLevel: "<0.2%", origin: "Occitanie, France", extraction: "Melange artisanal" },
    variants: [
      { weight: "10 sachets", price: 12.9, stock: 60 },
      { weight: "20 sachets", price: 22.9, stock: 35 },
    ],
    rating: 4.7,
    reviewCount: 67,
    badges: [],
    stock: 60,
    grower: { id: "g4", name: "Sophie Garnier", avatar: "/growers/sophie.svg", region: "Occitanie", verified: true },
    terroir: "Occitanie",
    harvestDate: "2026-01-05",
    labCertificateUrl: "#",
    organicCertifications: ["AB", "EU Bio", "Nature & Progres"],
    effects: ["Sommeil", "Relaxation"],
  },
  {
    id: "p5",
    slug: "baume-sport-cbd",
    name: "Baume Sport CBD",
    price: 24.9,
    images: ["/products/baume-sport-1.svg", "/products/baume-sport-2.svg"],
    category: "Baumes",
    categorySlug: "baumes",
    description: "Formule enrichie en CBD, arnica et menthol pour un soulagement cible des tensions musculaires et articulaires. Ce baume a la texture fondante penetre rapidement sans laisser de film gras. Ideal apres le sport ou en fin de journee.",
    shortDescription: "Baume musculaire au CBD, arnica et menthol, 50ml",
    features: { cbdPercent: "500mg", thcLevel: "<0.2%", origin: "Provence, France", extraction: "Infusion dans beurre de karite" },
    variants: [
      { weight: "50ml", price: 24.9, stock: 30 },
      { weight: "100ml", price: 39.9, stock: 15 },
    ],
    rating: 4.5,
    reviewCount: 42,
    badges: ["nouveau"],
    stock: 30,
    grower: { id: "g1", name: "Pierre Dumont", avatar: "/growers/pierre.svg", region: "Provence", verified: true },
    terroir: "Provence",
    harvestDate: "2025-11-20",
    labCertificateUrl: "#",
    organicCertifications: ["AB"],
    effects: ["Douleur", "Bien-etre"],
  },
  {
    id: "p6",
    slug: "bonbons-miel-cbd",
    name: "Bonbons Miel & CBD",
    price: 9.9,
    images: ["/products/bonbons-miel-1.svg", "/products/bonbons-miel-2.svg"],
    category: "Bonbons",
    categorySlug: "bonbons",
    description: "Bonbons artisanaux au miel de lavande et CBD, fabriques dans notre atelier provencal. Chaque bonbon contient 10mg de CBD pour un moment de douceur et de detente. Sans colorant artificiel, sans gluten.",
    shortDescription: "Bonbons artisanaux miel lavande, 10mg CBD par piece",
    features: { cbdPercent: "10mg/piece", thcLevel: "<0.2%", origin: "Provence, France", extraction: "Infusion" },
    variants: [
      { weight: "10 pieces", price: 9.9, stock: 100 },
      { weight: "20 pieces", price: 17.9, stock: 50 },
    ],
    rating: 4.4,
    reviewCount: 31,
    badges: [],
    stock: 100,
    grower: { id: "g1", name: "Pierre Dumont", avatar: "/growers/pierre.svg", region: "Provence", verified: true },
    terroir: "Provence",
    harvestDate: "2026-02-01",
    labCertificateUrl: "#",
    organicCertifications: ["AB", "EU Bio"],
    effects: ["Relaxation", "Bien-etre"],
  },
  {
    id: "p7",
    slug: "fleur-og-kush-cbd",
    name: "Fleur OG Kush CBD",
    price: 7.9,
    images: ["/products/og-kush-1.svg", "/products/og-kush-2.svg"],
    category: "Fleurs",
    categorySlug: "fleurs",
    description: "La OG Kush CBD est une variete indica dense et resineuse, aux aromes de pin et d'agrumes. Cultivee sous serre en Alsace avec un controle precis de l'humidite et de la temperature. Parfaite pour une relaxation profonde en fin de journee.",
    shortDescription: "Fleur indica dense, notes de pin, 20% CBD, culture sous serre",
    features: { cbdPercent: "20%", thcLevel: "<0.2%", origin: "Alsace, France", extraction: "Sechage lent" },
    variants: [
      { weight: "1g", price: 7.9, stock: 60 },
      { weight: "3g", price: 21.9, stock: 35 },
      { weight: "5g", price: 33.9, stock: 20 },
    ],
    rating: 4.7,
    reviewCount: 156,
    badges: ["best-seller"],
    stock: 60,
    grower: { id: "g3", name: "Thomas Muller", avatar: "/growers/thomas.svg", region: "Alsace", verified: true },
    terroir: "Alsace",
    harvestDate: "2026-01-10",
    labCertificateUrl: "#",
    organicCertifications: ["AB", "EU Bio"],
    effects: ["Relaxation", "Sommeil"],
  },
  {
    id: "p8",
    slug: "huile-cbd-bio-5",
    name: "Huile CBD Bio 5%",
    price: 19.9,
    images: ["/products/huile-5-1.svg", "/products/huile-5-2.svg"],
    category: "Huiles Bio",
    categorySlug: "huiles-bio",
    description: "L'huile CBD Bio 5% est ideale pour les debutants souhaitant decouvrir les bienfaits du CBD en douceur. Extraite de chanvre biologique breton, elle offre un spectre complet de cannabinoides dans une concentration accessible.",
    shortDescription: "Huile debutant full spectrum 5% CBD, flacon 10ml",
    features: { cbdPercent: "5%", thcLevel: "<0.2%", origin: "Bretagne, France", extraction: "CO2 supercritique" },
    variants: [
      { weight: "10ml", price: 19.9, stock: 55 },
      { weight: "30ml", price: 49.9, stock: 25 },
    ],
    rating: 4.6,
    reviewCount: 78,
    badges: [],
    stock: 55,
    grower: { id: "g2", name: "Marie Lefevre", avatar: "/growers/marie.svg", region: "Bretagne", verified: true },
    terroir: "Bretagne",
    harvestDate: "2025-12-28",
    labCertificateUrl: "#",
    organicCertifications: ["AB", "EU Bio", "Demeter"],
    effects: ["Bien-etre", "Relaxation"],
  },
  {
    id: "p9",
    slug: "resine-nepal-cream-cbd",
    name: "Resine Nepal Cream CBD",
    price: 9.9,
    images: ["/products/nepal-cream-1.svg", "/products/nepal-cream-2.svg"],
    category: "Resines",
    categorySlug: "resines",
    description: "Inspiree des techniques traditionnelles nepralaises, cette resine est pressee a la main pour une texture souple et une concentration elevee en CBD. Son profil terpenique est riche en myrcene et limonene.",
    shortDescription: "Resine traditionnelle, 25% CBD, texture souple et aromatique",
    features: { cbdPercent: "25%", thcLevel: "<0.3%", origin: "Alsace, France", extraction: "Pression manuelle" },
    variants: [
      { weight: "1g", price: 9.9, stock: 40 },
      { weight: "3g", price: 26.9, stock: 20 },
      { weight: "5g", price: 39.9, stock: 12 },
    ],
    rating: 4.8,
    reviewCount: 91,
    badges: ["nouveau"],
    stock: 40,
    grower: { id: "g3", name: "Thomas Muller", avatar: "/growers/thomas.svg", region: "Alsace", verified: true },
    terroir: "Alsace",
    harvestDate: "2026-02-05",
    labCertificateUrl: "#",
    organicCertifications: ["AB", "EU Bio"],
    effects: ["Relaxation", "Douleur"],
  },
  {
    id: "p10",
    slug: "infusion-detox-chanvre",
    name: "Infusion Detox Chanvre",
    price: 11.9,
    images: ["/products/infusion-detox-1.svg", "/products/infusion-detox-2.svg"],
    category: "Infusions",
    categorySlug: "infusions",
    description: "Un melange revitalisant de chanvre CBD, menthe poivree, gingembre et citron vert. Cette infusion detox aide a purifier l'organisme tout en apportant les bienfaits du CBD. Parfaite en matinee ou apres un repas copieux.",
    shortDescription: "Melange detox chanvre, menthe et gingembre, energisant",
    features: { cbdPercent: "6%", thcLevel: "<0.2%", origin: "Occitanie, France", extraction: "Melange artisanal" },
    variants: [
      { weight: "10 sachets", price: 11.9, stock: 45 },
      { weight: "20 sachets", price: 20.9, stock: 25 },
    ],
    rating: 4.3,
    reviewCount: 28,
    badges: [],
    stock: 45,
    grower: { id: "g4", name: "Sophie Garnier", avatar: "/growers/sophie.svg", region: "Occitanie", verified: true },
    terroir: "Occitanie",
    harvestDate: "2026-01-15",
    labCertificateUrl: "#",
    organicCertifications: ["AB", "EU Bio"],
    effects: ["Bien-etre", "Concentration"],
  },
  {
    id: "p11",
    slug: "fleur-amnesia-cbd",
    name: "Fleur Amnesia CBD",
    price: 7.5,
    images: ["/products/amnesia-1.svg", "/products/amnesia-2.svg"],
    category: "Fleurs",
    categorySlug: "fleurs",
    description: "L'Amnesia CBD est une sativa aux aromes intenses de citron et de terre. Cultivee en plein air dans le climat doux d'Occitanie, cette fleur offre un effet equilibre entre clarte mentale et detente physique.",
    shortDescription: "Fleur sativa citronnee, 16% CBD, culture plein air Occitanie",
    features: { cbdPercent: "16%", thcLevel: "<0.2%", origin: "Occitanie, France", extraction: "Sechage naturel" },
    variants: [
      { weight: "1g", price: 7.5, stock: 55 },
      { weight: "3g", price: 20.5, stock: 30 },
      { weight: "5g", price: 32.5, stock: 18 },
    ],
    rating: 4.5,
    reviewCount: 63,
    badges: [],
    stock: 55,
    grower: { id: "g4", name: "Sophie Garnier", avatar: "/growers/sophie.svg", region: "Occitanie", verified: true },
    terroir: "Occitanie",
    harvestDate: "2026-01-22",
    labCertificateUrl: "#",
    organicCertifications: ["AB", "EU Bio"],
    effects: ["Concentration", "Bien-etre"],
  },
  {
    id: "p12",
    slug: "huile-cbd-bio-30",
    name: "Huile CBD Bio 30%",
    price: 69.9,
    regularPrice: 89.9,
    images: ["/products/huile-30-1.svg", "/products/huile-30-2.svg"],
    category: "Huiles Bio",
    categorySlug: "huiles-bio",
    description: "Notre concentration la plus puissante, l'huile CBD Bio 30% s'adresse aux utilisateurs experimentes. Chaque goutte contient environ 7.5mg de CBD pour un dosage precis et une efficacite maximale.",
    shortDescription: "Huile premium 30% CBD, spectre complet, flacon 10ml",
    features: { cbdPercent: "30%", thcLevel: "<0.2%", origin: "Alsace, France", extraction: "CO2 supercritique" },
    variants: [
      { weight: "10ml", price: 69.9, stock: 15 },
      { weight: "30ml", price: 179.9, stock: 8 },
    ],
    rating: 4.9,
    reviewCount: 47,
    badges: ["promo"],
    stock: 15,
    grower: { id: "g3", name: "Thomas Muller", avatar: "/growers/thomas.svg", region: "Alsace", verified: true },
    terroir: "Alsace",
    harvestDate: "2025-12-10",
    labCertificateUrl: "#",
    organicCertifications: ["AB", "EU Bio"],
    effects: ["Douleur", "Sommeil", "Relaxation"],
  },
]

export const reviews: Review[] = [
  { id: "r1", author: "Jean-Pierre M.", rating: 5, date: "2026-02-10", text: "Qualite exceptionnelle ! La resine Gold Hash est devenue mon incontournable pour la relaxation du soir. On sent vraiment la difference avec un produit de producteur local.", productName: "Resine Gold Hash CBD", verified: true },
  { id: "r2", author: "Camille D.", rating: 5, date: "2026-02-08", text: "L'huile 15% m'a changé la vie pour mon sommeil. Je dors enfin des nuits completes. Merci a Thomas et son equipe en Alsace !", productName: "Huile CBD Bio 15%", verified: true },
  { id: "r3", author: "Laurent B.", rating: 4, date: "2026-02-05", text: "Tres satisfait de la Lemon Haze. Les aromes citronnees sont incroyables, on sent le travail de la productrice bretonne. Livraison rapide en plus.", productName: "Fleur Lemon Haze CBD", verified: true },
  { id: "r4", author: "Nathalie R.", rating: 5, date: "2026-02-01", text: "L'infusion Nuit Paisible est parfaite avant le coucher. Un moment de pure detente. J'adore pouvoir voir d'ou viennent les ingredients sur la fiche produit.", productName: "Infusion Nuit Paisible", verified: true },
  { id: "r5", author: "Marc V.", rating: 5, date: "2026-01-28", text: "Le baume sport est devenu essentiel apres mes sessions de velo. Soulagement immediat et texture agreable. Bravo pour la transparence sur les certificats labo.", productName: "Baume Sport CBD", verified: true },
  { id: "r6", author: "Isabelle F.", rating: 4, date: "2026-01-25", text: "Premiere commande et je suis ravie. Les bonbons sont delicieux et l'effet relaxant se fait sentir doucement. J'apprecie de connaitre le producteur.", productName: "Bonbons Miel & CBD", verified: true },
]

export const orders: Order[] = [
  {
    id: "o1",
    reference: "OURS-2026-0847",
    date: "2026-02-10",
    status: "shipped",
    items: [
      { name: "Resine Gold Hash CBD - 3g", quantity: 1, price: 23.9 },
      { name: "Huile CBD Bio 15% - 10ml", quantity: 1, price: 39.9 },
    ],
    subtotal: 63.8,
    shipping: 0,
    total: 63.8,
    trackingNumber: "8R12345678901",
    carrier: "Colissimo",
  },
  {
    id: "o2",
    reference: "OURS-2026-0812",
    date: "2026-01-28",
    status: "delivered",
    items: [
      { name: "Fleur Lemon Haze CBD - 5g", quantity: 2, price: 27.5 },
      { name: "Infusion Nuit Paisible - 20 sachets", quantity: 1, price: 22.9 },
    ],
    subtotal: 77.9,
    shipping: 0,
    total: 77.9,
    trackingNumber: "8R98765432109",
    carrier: "Colissimo",
  },
  {
    id: "o3",
    reference: "OURS-2026-0798",
    date: "2026-01-15",
    status: "delivered",
    items: [
      { name: "Bonbons Miel & CBD - 20 pieces", quantity: 1, price: 17.9 },
    ],
    subtotal: 17.9,
    shipping: 4.9,
    total: 22.8,
  },
]

export const FREE_SHIPPING_THRESHOLD = 49
